twitter/twitter-text

js/twitter-text.js

Immaterial change, but allows using `twitter-text` for 3rd-party posts with longer max lengths. I want to check for invalid characters too.

refactor has invalid characters into new method

---

java/src/com/twitter/Regex.java

Hashtags allowed a lot more characters than alphabet now. These changed constant names are all private, so it shouldn't have a backward-compatibility issue.

Rename alpha to letter

---

objc/twitter-text.podspec

The existing podpec references https://github.com/twitter/twitter-text-objc which doesn't include the latest version tags.

Update pod spec to reference unified git repo location

---

rb/lib/twitter-text/rewriter.rb

Accessing a property via an indexer was deprecated in sferik's twitter gem here: https://github.com/sferik/twitter/commit/2ab6c0d546b7c1d3635ac9c319fb5c2aa2514da0.
In our code base, we use the twitter-text gem to rewrite tweets, passing in entities initialized via sferik's twitter gem. This is now causing a lot of deprecation warnings throughout our logs:
```
/home/rof/cache/bundler/ruby/2.1.0/gems/twitter-text-1.10.0/lib/twitter-text/rewriter.rb:12:in `block in rewrite_entities': [DEPRECATION] #[:indices] is deprecated. Use #indices to fetch the value.
/home/rof/cache/bundler/ruby/2.1.0/gems/twitter-text-1.10.0/lib/twitter-text/rewriter.rb:14:in `block in rewrite_entities': [DEPRECATION] #[:indices] is deprecated. Use #indices to fetch the value. …
```

Support sferik/twitter's deprecation of entity[:indices]

---

js/twitter-text.js

Currently the library only works in the browser because you are exporting to the `window` object. 
This fix changes that to export to the global scope, regardless of what it is called. Thereby you can run this in node or embedded V8.

Export to global scope in server or embedded environments

---

rb/lib/twitter-text/autolink.rb

This fixes a bug I was seeing when I passed the option `hashtag_class: nil` to the `auto_link` method with a hebrew hashtag as the argument (hebrew is written from right to left):
```
[Dev]> Twitter::Autolink.auto_link("#ביתכנסת #קופנהגן", hashtag_class: nil)
NoMethodError: undefined method `+' for nil:NilClass
```
The change is to make sure the variable `hashtag_class` is a string before we try to append `' rtl'` to it. Same example with the changes works as expected:
```
[Dev]> Twitter::Autolink.auto_link("#ביתכנסת #קופנהגן", hashtag_class: nil)
=> "<a class=\" rtl\" href=\"https://twitter.com/#!/search?q=%23ביתכנסת\" rel=\"nofollow\" title=\"#ביתכנסת\">#ביתכנסת</a> <a class=\" rtl\" href=\"https://twitter.com/#!/search?q=%23קופנהגן\" rel=\"nofollow\" title=\"#קופנהגן\">#קופנהגן</a>" …
```

Ruby bugfix for autolinking RTL hashtags with :hashtag_class => nil

---

js/twitter-text.js

This reverts commit aae2099e8426922af269adde9e064e70511dbe77.
aae2099 was originally merged by be92738a1a928
While this change passes tests, it breaks twitter.com with:
"Uncaught TypeError: undefined is not a function"
Hopefully those who need this can maintain their own fork for now.
/cc @jeroenooms

Revert "Export to global scope in server or embedded environments"

---

conformance/autolink.yml
java/src/com/twitter/Regex.java
js/twitter-text.js
objc/lib/TwitterText.m
rb/lib/twitter-text/regex.rb

support@example.com should not link @example
rt@example should link @example

Don't linkify RT@example when common email chars precede the RT

---

conformance/validate.yml
java/src/com/twitter/Validator.java
js/twitter-text.js
objc/lib/TwitterText.m
objc/test/json-conformance/tlds.json
objc/test/json-conformance/validate.json
rb/lib/twitter-text/validation.rb

t.co will be https-only soon, including http short-links, so I've updated all http length checks to be 23 characters instead of 22. This twitter-text change will be deployed ahead of the t.co update. Clients will briefly "waste" 1 character until t.co switches to https.

t.co will be https only soon

---

rb/lib/twitter-text/autolink.rb
rb/lib/twitter-text/hash_helper.rb

By using the 'destructive' symbolize_keys! method, the caller gets an unexpected behaviour
where the arguments passed are modified by the Autolink methods. This side-effect is better
to avoid in general.
BTW, fix the non-destructive symbolize_keys method.
All conformances tests are still OK.

Do not alter arguments passed to Twitter::Autolink methods

---

conformance/autolink.yml
java/src/com/twitter/Regex.java
java/tests/com/twitter/RegexTest.java
js/twitter-text.js
objc/lib/TwitterText.m
rb/lib/twitter-text/regex.rb

Tweeting this key sequence: "#\ufe0f\u20e3"
https://twitter.com/tom_demo/status/661683876973031424
Or this key sequence: "#\u20e3"
https://twitter.com/tom_demo/status/661684939004317696
Should result in the keycap Emoji for a hash sign, not an actual linked hashtag, which is broken and renders incorrectly anyway.

Ignore Emojified # or keycap # when scanning for hashtags

---

js/twitter-text.js

So here we go again, another escaped unicode partial inside a string literal. This gets exploded by the minifier, and then normalized by some browsers/proxies/etc..
This is the root cause of this bug: 
https://twitter.com/jamesreggio/status/705092597212192768
The solution is to put escape partials inside RegEx literals, or build them using other means.

Use RegEx literal instead of String literal

---

js/test/node_tests.js

This is in response to @megaserg  's comment on https://github.com/twitter/twitter-text/pull/105

Unit test to watch for unicode escapes in string literals

---

js/test/tests.js

I had to do some testing on the getTweetLength javascript function for a defect in my own system. 
In the process I wrote some unit tests to confirm my own assumptions about how getTweetLength behaved with long URLs. 
Hopefully you find the unit tests useful as well.

Added Javascript unit tests for twttr.txt.getTweetLength

---

java/src/com/twitter/Regex.java

IsCyrillic, a char class, is not available for `java.util.regex` on
Android and when a regex contains it is passed as an argument of
`java.util.regex.Pattern#complie`, the method throws
`IllegalArgumentException`.
To avoid this, replaced `\p{IsCyrillic}` with `\u0400-\u04ff`
http://unicode.org/charts/PDF/U0400.pdf
Following issues may be related to this PR.
#139 #111

Replace IsCyrillic with unicode range

---

conformance/extract.yml
objc/lib/TwitterText.m
objc/test/json-conformance/extract.json

URLs that contain a t.co in the referer were not being properly parsed
in objc due to a missing anchor in the TWUValidTCOURL regex. The result
was that a URL of the form:
http://foo.com/xyz?referer=http://t.co/abcde
would be parsed as http://t.co/abcde
The java, js, and ruby implementations have the correct regex. Also
added a test case for this style of URL.

Properly parse URLs with t.co referer

---

js/twitter-text.js

The RegExp for `twttr.txt.regexen.validateUrlUnicodeDomain` is broken as there are typos for the syntax of inner variables. 
This PR fixes the faulty regular expression, therefore also fixing the `twttr.txt.isValidUrl` function

fixes 'validateUrlDomain' regex

---

objc/TwitterText.xcodeproj/project.pbxproj

spoke with Tanner about this, and also investigated other Twitter projects, and i think this is the appropriate thing to do; code-signing this .framework product should happen at the embed stage when the app is installed on a developer device or during Archive

fix: project.pbxproj settings: make DEVELOPMENT_TEAM generic

---

objc/TwitterText.xcodeproj/project.pbxproj

the change to remove the DEVELOPMENT_TEAM was necessary but not sufficient.
this change was performed by not from the settings panel, but rather the checkbox in the general panel for the project target.

no CODE_SIGN_IDENTITY + use 'ProvisioningStyle = Manual'

---

objc/lib/TwitterText.h
objc/lib/TwitterText.m

This change adds nullability and array generic annotations to improve Swift compatibility. The `__has_feature` macro is used to ensure the compiler is new enough to support those annotations, and falls back if it doesn't. This technique is similar the one used in Fabric.

Nullability and generic annotations for Swift compatibility

---

conformance/extract.yml
java/src/com/twitter/Regex.java
js/twitter-text.js
objc/lib/TwitterText.m
rb/lib/twitter-text/regex.rb

Wikipedia sometimes uses a unicode "en dash" (U+2013) in URL paths. This PR adds support to the URL extractor for this character. For example of a broken URL extraction, see https://twitter.com/raymastian/status/888524025592512512
closes #132

add support for en-dash u+2013 in URL paths

---

objc/tests/TwitterTextTests.m

when built in Xcode with recommended warnings enabled, using anything but %tu for NSUInteger is flagged as an issue.

objc: TwitterTextTests.m: silence NSUInteger format warnings

---

js/src/linkToTextWithSymbol.js

Using global variable `twttr.txt` directly throws error on node.js environment
https://github.com/twitter/twitter-text/blob/58188ccf8d083722d08d9b2d17686eb82d74ebdf/js/src/linkToTextWithSymbol.js#L9
```js
import twitter from './build/twitter-text';
const text = '@twitterdev';
const linkified = twitter.autoLink(text); // ReferenceError: twttr is not defined
console.log(linkified);
```

Fix linkToTextWithSymbol.js from accessing global variable

---

objc/README.rdoc

The Cocoapods link in the README was linking to the deprecated version. I had mistakenly used this version only to find out that it was not the correct one.

Update Cocoapods link in README

---

rb/Rakefile
rb/lib/assets/tld_lib.yml
rb/twitter-text.gemspec

This is only an issue when packaging the ruby gem. The tld_lib.yml file
was a symlink which was missing from the gem.

Fix dangling symlink (Issue #211)

---

rb/CHANGELOG.md
rb/README.md
rb/lib/twitter-text/autolink.rb
rb/lib/twitter-text/configuration.rb
rb/lib/twitter-text/deprecation.rb
rb/lib/twitter-text/extractor.rb
rb/lib/twitter-text/hash_helper.rb
rb/lib/twitter-text/hit_highlighter.rb
rb/lib/twitter-text/regex.rb
rb/lib/twitter-text/rewriter.rb
rb/lib/twitter-text/unicode.rb
rb/lib/twitter-text/validation.rb
rb/lib/twitter-text/weighted_range.rb
rb/spec/autolinking_spec.rb
rb/spec/configuration_spec.rb
rb/spec/extractor_spec.rb
rb/spec/hithighlighter_spec.rb
rb/spec/regex_spec.rb
rb/spec/rewriter_spec.rb
rb/spec/spec_helper.rb
rb/spec/unicode_spec.rb
rb/spec/validation_spec.rb
rb/test/conformance_test.rb
rb/twitter-text.gemspec

The popular Twitter gem (https://github.com/sferik/twitter) uses the
Twitter::Configuration namespace and users are reporting that our new
Twitter::Configuration class is conflicting with that namespace.
This patch changes our top-level namespace from Twitter to
Twitter::TwitterText:: to resolve this conflict and prevent further
conflicts in the future. Because this is a breaking change for clients
written against older versions of the library, the version has been
bumped to 2.1. This namespace more closely matches the namespace we use
in our Java implementation, too (com.twitter.twittertext)
There's also a new CHANGELOG.md file that details important changes in
this revision and will be updated going forward.

[#211] Update top-level namespace to Twitter::TwitterText::

---

js/package.json

The previous homepage URL redirects to https://github.com/twitter-archive/twitter-text-js , which just contains a deprecation notice pointing to this monorepo.
This patch updates the homepage URL in `package.json`, which should also fix the homepage URL on npm: https://www.npmjs.com/package/twitter-text

Point twitter-text/js homepage URL to monorepo

---

objc/CHANGELOG.md
objc/Rakefile
objc/TwitterText.xcodeproj/project.pbxproj
objc/TwitterText.xcodeproj/xcshareddata/xcschemes/TwitterText Mac.xcscheme
objc/lib/TwitterText.m
objc/resources/Info.plist

Includes the following:
- New changelog to call out significant changes in releases (see
CHANGELOG.md)
- Refactored use of IFUnicodeURL; removed embedded framework and added
source files directly. This will unblock the release of the cocoapod.
- Cross-platform support for iOS and macOS (Issue #228)
- Rakefile now supports running both iOS and macOS conformance tests.

Update for 2.0.1 objc release

---

conformance/extract.yml
conformance/validate.yml
java/README.md
java/pom.xml
java/src/main/java/com/twitter/twittertext/Regex.java
java/src/main/java/com/twitter/twittertext/Validator.java
java/src/test/java/com/twitter/twittertext/ConformanceTest.java
java/src/test/java/com/twitter/twittertext/RegexTest.java
java/src/test/java/com/twitter/twittertext/ValidatorTest.java
js/src/extractUrlsWithIndices.js
js/src/regexp/index.js
js/test/conformance.html
js/test/tests.js
objc/lib/TwitterText.m
objc/tests/TwitterTextTests.m
objc/tests/json-conformance/extract.json
objc/tests/json-conformance/validate.json
rb/lib/twitter-text/extractor.rb
rb/lib/twitter-text/regex.rb

[Java] Proxy deprecated Validator methods to use TwitterTextParser.

[All] Extract urls with a ccTLD but without a protocol/path.

---

js/package.json
js/src/lib/idna.js

startsWith needs a polyfill on older browsers. We don't really need it as substring works fine. Links #242.

Use substring instead of startsWith for punycode check

---

objc/CHANGELOG.md

Includes the following:
- Domains with country code TLDs that are not prefixed by a protocol
will now be extracted as a URL entity. Previously .cc and .tv were
special-cased. This may result in some tweets getting longer: a
short domain like "twitter.co" will be counted as 23 characters.

Update for 2.0.4 objc release

---

objc/CHANGELOG.md
objc/ThirdParty/IFUnicodeURL/Tests/NSURL+IFUnicodeURLTest.m
objc/TwitterText.xcodeproj/project.pbxproj
objc/resources/TwitterText.modulemap

- Fixes project files to address analyzer warnings, problems with groups (and missing files)
- IFUnicodeURL.h is the umbrella header for the IFUnicodeURL.xcodeproja nd as such, should not be included as a file in the TwitterText.xcodeproj
- Fixes project files to address problems using the framework on macOS

Update for 2.0.5 objc release

---

rb/lib/twitter-text/autolink.rb
rb/spec/autolinking_spec.rb

This fixes twitter/twitter-text#275

Ruby: Fix auto_link so that it doesn't remove emoji

---

rb/twitter-text.gemspec

To stop the following warning appearing when you install the rub gem
> NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement.
> It will be removed on or after 2018-12-01.  Gem::Specification#has_rdoc=
> called from twitter-text/rb/twitter-text.gemspec:18.

Ruby: Remove deprecated `has_rdoc` call
